### ISSUE TITLE
const String -> u32 ?

### ISSUE THREAD

**Issue by dakom** [CasualX/obfstr#28]
Heya, I came across your article at https://casualhacks.net/blog/2020-05-31/compiletime-processing/

Was wondering if you've looked into doing this for creating compile-time hashes from strings?

For example, I'd like to be able to do `const U_POSITION:u32 = hash!("u_color");` and know that it's the same value as some other usage elsewhere. Speed and avoiding collisions are important, but it doesn't need to be cryptographically secure.

**Comment by CasualX** [comment]
That article is a bit outdated by now, there's already a [`hash!`](https://docs.rs/obfstr/0.2.1/obfstr/macro.hash.html) macro. Note that if you're using it in a const context you can simply use the const fn [`hash`](https://docs.rs/obfstr/0.2.1/obfstr/fn.hash.html) instead of the macro. The macro simply forces compiletime evaluation where the compiler would default to invoking it at runtime.

However avoiding collisions is not possible with compiletime string hashing like this as it requires global understanding of all the other string hashes.

If avoiding collisions is 100% important you're probably looking at string interning, which is trivial in this case as the compiler will already do it for you if you use static objects instead of string literals, eg. `pub static U_COLOR: &str = "u_color";`. You can use `U_COLOR.as_ptr() as usize` as a globally unique id for the "u_color" string.
